# TODO: Update userid
gitUserId: aniketk-crest
# TODO: Update repoid
gitRepoId: appdynamicscloud-go-client
files:
  client.mustache:
    templateType: SupportingFiles
    destinationFilename: client.go
  configuration.mustache:
    templateType: SupportingFiles
    destinationFilename: configuration.go
