gitUserId: cisco-open
gitRepoId: appd-cloud-go-client
files:
  client.mustache:
    templateType: SupportingFiles
    destinationFilename: client.go
  configuration.mustache:
    templateType: SupportingFiles
    destinationFilename: configuration.go
