name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run script file
        run: |
         chmod +x ./script.sh
         ./script.sh
        shell: bash
        
      - name: Commit report
        run: |
          git config --global user.name 'AniketK-Crest'
          git config --global user.email 'aniketk-crest@users.noreply.github.com'
          git commit -am "Automated commit"
          git push
