name: CI

on:
  push:
    branches: [ "arjun-github-action" ]
  pull_request:
    branches: [ "arjun-github-action" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      openApiVersion:
        description: 'OpenApi Generator Version'
        required: false
        default: '6.2.1'
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run script file
        run: |
         chmod +x script.sh
         sh ./script.sh ${{ github.event.inputs.openApiVersion }}
        shell: bash
        
      - name: Commit report
        run: |
          git add .
          git commit -m "Automated commit"
          git push origin arjun-github-action
